import archiver from "archiver";
import { Readable } from "stream";
import type { Project, FlowNode, SectionNodeData, PageNodeData, ProjectSettings } from "@/types";

/**
 * Export configuration options
 */
export interface ExportOptions {
  includeComponents: boolean;
  includeStyles: boolean;
  includeConfigs: boolean;
  format: "nextjs" | "react" | "html";
}

/**
 * Generated file content
 */
export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Default Tailwind config content
 */
function generateTailwindConfig(settings?: ProjectSettings): string {
  const colors = settings?.color_palette || {
    primary: "#3B82F6",
    secondary: "#6B7280",
    accent: "#F59E0B",
    background: "#FFFFFF",
    text: "#111827",
  };

  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '${colors.primary}',
        secondary: '${colors.secondary}',
        accent: '${colors.accent}',
        background: '${colors.background}',
        foreground: '${colors.text}',
      },
      fontFamily: {
        heading: ['${settings?.typography?.heading_font || "Inter"}', 'sans-serif'],
        body: ['${settings?.typography?.body_font || "Inter"}', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
`;
}

/**
 * Generate globals.css with custom properties
 */
function generateGlobalStyles(settings?: ProjectSettings): string {
  const colors = settings?.color_palette || {
    primary: "#3B82F6",
    secondary: "#6B7280",
    accent: "#F59E0B",
    background: "#FFFFFF",
    text: "#111827",
  };

  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-accent: ${colors.accent};
  --color-background: ${colors.background};
  --color-text: ${colors.text};
  --font-heading: '${settings?.typography?.heading_font || "Inter"}', sans-serif;
  --font-body: '${settings?.typography?.body_font || "Inter"}', sans-serif;
}

body {
  background-color: var(--color-background);
  color: var(--color-text);
  font-family: var(--font-body);
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
}
`;
}

/**
 * Generate package.json for the exported project
 */
function generatePackageJson(projectName: string): string {
  return JSON.stringify(
    {
      name: projectName.toLowerCase().replace(/\s+/g, "-"),
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^14.0.0",
        react: "^18.2.0",
        "react-dom": "^18.2.0",
      },
      devDependencies: {
        typescript: "^5.0.0",
        "@types/node": "^20.0.0",
        "@types/react": "^18.2.0",
        "@types/react-dom": "^18.2.0",
        tailwindcss: "^3.4.0",
        postcss: "^8.4.0",
        autoprefixer: "^10.4.0",
      },
    },
    null,
    2
  );
}

/**
 * Generate tsconfig.json
 */
function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: {
          "@/*": ["./*"],
        },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

/**
 * Generate next.config.js
 */
function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
`;
}

/**
 * Generate postcss.config.js
 */
function generatePostCssConfig(): string {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
}

/**
 * Generate layout.tsx for Next.js App Router
 */
function generateLayout(projectName: string, settings?: ProjectSettings): string {
  const fonts = settings?.typography || { heading_font: "Inter", body_font: "Inter" };

  return `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by FlowForge',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`;
}

/**
 * Generate a page component from a PageNode
 */
function generatePage(pageNode: PageNodeData, sections: SectionNodeData[]): string {
  const componentName = pageNode.name
    .replace(/[^a-zA-Z0-9]/g, "")
    .replace(/^./, (c) => c.toUpperCase());

  // Build imports based on sections
  const sectionImports = sections.map((section) => {
    const sectionComponentName = getSectionComponentName(section.section_type);
    return `import { ${sectionComponentName} } from '@/components/sections/${section.section_type}'`;
  });

  // Build section components
  const sectionComponents = sections.map((section) => {
    const sectionComponentName = getSectionComponentName(section.section_type);
    return `      <${sectionComponentName} />`;
  });

  return `${sectionImports.length > 0 ? sectionImports.join("\n") + "\n\n" : ""}export default function ${componentName}Page() {
  return (
    <main className="min-h-screen">
${sectionComponents.length > 0 ? sectionComponents.join("\n") : "      {/* Add your sections here */}"}
    </main>
  )
}
`;
}

/**
 * Get component name for a section type
 */
function getSectionComponentName(sectionType: string): string {
  return sectionType
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

/**
 * Generate a section component
 */
function generateSectionComponent(section: SectionNodeData): string {
  const componentName = getSectionComponentName(section.section_type);

  // If the section has generated content, use it
  if (section.content?.generated) {
    return section.content.generated;
  }

  // Otherwise, generate a placeholder based on section type
  const placeholders: Record<string, string> = {
    hero: `export function ${componentName}() {
  return (
    <section className="py-20 px-4 bg-gradient-to-b from-primary/10 to-background">
      <div className="max-w-6xl mx-auto text-center">
        <h1 className="text-5xl font-bold mb-6 font-heading">
          Welcome to Our Platform
        </h1>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          Discover the power of our solution and transform your business today.
        </p>
        <div className="flex gap-4 justify-center">
          <button className="px-8 py-3 bg-primary text-white rounded-lg font-semibold hover:bg-primary/90 transition">
            Get Started
          </button>
          <button className="px-8 py-3 border border-primary text-primary rounded-lg font-semibold hover:bg-primary/10 transition">
            Learn More
          </button>
        </div>
      </div>
    </section>
  )
}`,
    features: `export function ${componentName}() {
  const features = [
    { title: 'Feature 1', description: 'Description of feature 1' },
    { title: 'Feature 2', description: 'Description of feature 2' },
    { title: 'Feature 3', description: 'Description of feature 3' },
  ]

  return (
    <section className="py-20 px-4">
      <div className="max-w-6xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12 font-heading">
          Our Features
        </h2>
        <div className="grid md:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div key={index} className="p-6 rounded-lg border hover:shadow-lg transition">
              <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
              <p className="text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}`,
    testimonials: `export function ${componentName}() {
  const testimonials = [
    { name: 'John Doe', role: 'CEO', content: 'Amazing product!' },
    { name: 'Jane Smith', role: 'Designer', content: 'Love using this.' },
  ]

  return (
    <section className="py-20 px-4 bg-secondary/5">
      <div className="max-w-6xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12 font-heading">
          What Our Customers Say
        </h2>
        <div className="grid md:grid-cols-2 gap-8">
          {testimonials.map((testimonial, index) => (
            <div key={index} className="p-6 bg-background rounded-lg shadow">
              <p className="text-lg mb-4">"{testimonial.content}"</p>
              <div>
                <p className="font-semibold">{testimonial.name}</p>
                <p className="text-muted-foreground text-sm">{testimonial.role}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}`,
    cta: `export function ${componentName}() {
  return (
    <section className="py-20 px-4 bg-primary text-white">
      <div className="max-w-4xl mx-auto text-center">
        <h2 className="text-3xl font-bold mb-6 font-heading">
          Ready to Get Started?
        </h2>
        <p className="text-xl mb-8 opacity-90">
          Join thousands of satisfied customers today.
        </p>
        <button className="px-8 py-3 bg-white text-primary rounded-lg font-semibold hover:bg-white/90 transition">
          Start Free Trial
        </button>
      </div>
    </section>
  )
}`,
    footer: `export function ${componentName}() {
  return (
    <footer className="py-12 px-4 bg-foreground text-background">
      <div className="max-w-6xl mx-auto">
        <div className="grid md:grid-cols-4 gap-8">
          <div>
            <h3 className="font-bold text-lg mb-4">Company</h3>
            <ul className="space-y-2">
              <li><a href="#" className="hover:underline">About</a></li>
              <li><a href="#" className="hover:underline">Careers</a></li>
              <li><a href="#" className="hover:underline">Contact</a></li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold text-lg mb-4">Product</h3>
            <ul className="space-y-2">
              <li><a href="#" className="hover:underline">Features</a></li>
              <li><a href="#" className="hover:underline">Pricing</a></li>
              <li><a href="#" className="hover:underline">Docs</a></li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold text-lg mb-4">Legal</h3>
            <ul className="space-y-2">
              <li><a href="#" className="hover:underline">Privacy</a></li>
              <li><a href="#" className="hover:underline">Terms</a></li>
            </ul>
          </div>
          <div>
            <h3 className="font-bold text-lg mb-4">Connect</h3>
            <ul className="space-y-2">
              <li><a href="#" className="hover:underline">Twitter</a></li>
              <li><a href="#" className="hover:underline">LinkedIn</a></li>
              <li><a href="#" className="hover:underline">GitHub</a></li>
            </ul>
          </div>
        </div>
        <div className="mt-12 pt-8 border-t border-background/20 text-center">
          <p>&copy; 2024 Company Name. All rights reserved.</p>
        </div>
      </div>
    </footer>
  )
}`,
  };

  return placeholders[section.section_type] || `export function ${componentName}() {
  return (
    <section className="py-20 px-4">
      <div className="max-w-6xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-8 font-heading">
          ${section.name}
        </h2>
        ${section.description ? `<p className="text-center text-muted-foreground">${section.description}</p>` : ""}
      </div>
    </section>
  )
}`;
}

/**
 * Generate all files for export
 */
export function generateExportFiles(
  project: Project,
  nodes: FlowNode[],
  options: ExportOptions
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Get page nodes and section nodes
  const pageNodes = nodes.filter((n) => n.type === "page");
  const sectionNodes = nodes.filter((n) => n.type === "section");

  // Config files
  if (options.includeConfigs) {
    files.push({ path: "package.json", content: generatePackageJson(project.name) });
    files.push({ path: "tsconfig.json", content: generateTsConfig() });
    files.push({ path: "next.config.js", content: generateNextConfig() });
    files.push({ path: "postcss.config.js", content: generatePostCssConfig() });
    files.push({ path: "tailwind.config.js", content: generateTailwindConfig(project.settings) });
  }

  // Styles
  if (options.includeStyles) {
    files.push({ path: "app/globals.css", content: generateGlobalStyles(project.settings) });
  }

  // Layout
  files.push({ path: "app/layout.tsx", content: generateLayout(project.name, project.settings) });

  // Pages
  for (const pageNode of pageNodes) {
    const pageData = pageNode.data as PageNodeData;
    const route = pageData.route === "/" ? "" : pageData.route.replace(/^\//, "");
    const pagePath = route ? `app/${route}/page.tsx` : "app/page.tsx";

    // Find sections for this page
    const pageSections = sectionNodes
      .filter((s) => pageData.section_ids?.includes(s.id))
      .map((s) => s.data as SectionNodeData);

    files.push({ path: pagePath, content: generatePage(pageData, pageSections) });
  }

  // Section components
  if (options.includeComponents) {
    const uniqueSectionTypes = new Set<string>();
    for (const node of sectionNodes) {
      const sectionData = node.data as SectionNodeData;
      if (!uniqueSectionTypes.has(sectionData.section_type)) {
        uniqueSectionTypes.add(sectionData.section_type);
        files.push({
          path: `components/sections/${sectionData.section_type}.tsx`,
          content: generateSectionComponent(sectionData),
        });
      }
    }
  }

  // README
  files.push({
    path: "README.md",
    content: `# ${project.name}

Generated by [FlowForge](https://flowforge.dev)

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

3. Open [http://localhost:3000](http://localhost:3000) in your browser.

## Project Structure

- \`app/\` - Next.js App Router pages
- \`components/\` - React components
- \`public/\` - Static assets

## Built With

- [Next.js](https://nextjs.org/)
- [Tailwind CSS](https://tailwindcss.com/)
- [TypeScript](https://www.typescriptlang.org/)
`,
  });

  return files;
}

/**
 * Create a zip archive from generated files
 */
export async function createZipArchive(files: GeneratedFile[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const archive = archiver("zip", { zlib: { level: 9 } });

    archive.on("data", (chunk) => chunks.push(chunk));
    archive.on("end", () => resolve(Buffer.concat(chunks)));
    archive.on("error", reject);

    // Add files to archive
    for (const file of files) {
      archive.append(file.content, { name: file.path });
    }

    archive.finalize();
  });
}

/**
 * Create a readable stream from generated files (for streaming response)
 */
export function createZipStream(files: GeneratedFile[]): Readable {
  const archive = archiver("zip", { zlib: { level: 9 } });

  for (const file of files) {
    archive.append(file.content, { name: file.path });
  }

  archive.finalize();

  return archive as unknown as Readable;
}
